"""
CLARA — Dummy Discharge PDF Generator
Generates 3 hospital visits for patient Galicia, Deogracias Jr.
for testing the EncountersPanel timeline feature.

Output: ~/Desktop/Patients/GALICIA_DEOGRACIAS_JR/
  - discharge_2023_04_visit1.pdf   (NSTEMI + T/C Appendicitis — baseline)
  - discharge_2023_10_visit2.pdf   (Chest pain recurrence + early CHF)
  - discharge_2024_03_visit3.pdf   (Decompensated CHF + CKD progression)

Run: python generate_dummy_discharge_pdfs.py
"""

import os
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.enums import TA_LEFT, TA_CENTER

OUT_DIR = os.path.join(os.path.expanduser("~"), "Desktop", "Patients", "GALICIA_DEOGRACIAS_JR")

# ── Discharge summaries ────────────────────────────────────────────────────────

VISIT_1 = """QUIRINO MEMORIAL MEDICAL CENTER
DISCHARGE SUMMARY / MEDICAL ABSTRACT

NAME: GALICIA, DEOGRACIAS JR.
AGE: 53  SEX: M  STATUS: MARRIED  HOSPITAL NO: 978305
SERVICE/S: MEDICINE  ROOM/WARD: PHASE 9
ATTENDING PHYSICIAN: DR. PAREJA, NOEL JOSEPH S.
DATE ADMITTED: 04/15/23  TIME ADMITTED: 10:45 AM
DATE DISCHARGED: 04/23/23
CONDITION UPON DISCHARGE: [x] RECOVERED

ADMITTING DIAGNOSIS: ACUTE CORONARY SYNDROME NON ST ELEVATION MYOCARDIAL INFARCTION SEPTAL WALL TIMI 4 KILIP 1 GRACE SCORE 103; CEREBROVASCULAR DISEASE BLEED MRS 3, S/P DECOMPRESSIVE HEMICRANIECTOMY, LEFT (2015, QMMC); T/C ACUTE APPENDICITIS

FINAL DIAGNOSIS: ACUTE CORONARY SYNDROME NON ST ELEVATION MYOCARDIAL INFARCTION SEPTAL WALL TIMI 4 KILIP 1 GRACE SCORE 79; CEREBROVASCULAR DISEASE BLEED MRS 3, S/P DECOMPRESSIVE HEMICRANIECTOMY, LEFT (2015, QMMC)

CHIEF COMPLAINT: ABDOMINAL PAIN

HISTORY OF PRESENT ILLNESS: 3 DAYS PTA, PATIENT NOTED ABDOMINAL PAIN, LEFT UPPER QUADRANT PAIN, THEN GRADUALLY TO RIGHT LOWER QUADRANT, WITH NO OTHER SYMPTOMS NOTED SUCH AS FEVER, CHEST PAIN, DYSURIA, VOMITING. SELF MEDICATED WITH HNBB AFFORDING TEMPORARY RELIEF. RECURRENCE OF SYMPTOMS PROMPTED CONSULT.

PAST MEDICAL HISTORY: HYPERTENSION (2015) - MAINTAINED ON ENALAPRIL 5MG/TAB OD, ISMN 30MG/TAB OD, ASA 80MG/TAB OD, CLOPIDOGREL 75MG/TAB OD; CHRONIC CVD INFARCT (2015) - S/P DECOMPRESSIVE HEMICRANIECTOMY (2015, QMMC)

PHYSICAL EXAMINATION: BP 130/80, HR 100, RR 20, TEMP 36.7, SpO2 98%. AWAKE, COHERENT, NOT IN CARDIORESPIRATORY DISTRESS. ANICTERIC SCLERAE, PINK PALPEBRAL CONJUNCTIVAE, NO CERVICAL LYMPHADENOPATHIES. SYMMETRIC CHEST EXPANSION, NO RETRACTIONS, CLEAR BREATH SOUNDS. ADYNAMIC PRECORDIUM, NO MURMURS. ABDOMEN FLABBY, SOFT, DIRECT AND REBOUND TENDERNESS RLQ.

LABORATORY DATA:
CBC (04/15): WBC 9.6, HGB 145, HCT 0.43, PLT 227. TROP I (04/15): 1.05 (H). CKMB (04/15): 18. CREATININE (04/15): 1.1 MG/DL. POTASSIUM (04/15): 3.8 MEQ/L. SODIUM (04/15): 138 MEQ/L. ECG (04/15): NSR, T WAVE INVERSION V1-V3. WAB ULTRASOUND (04/15): NEGATIVE FOR APPENDICITIS. WAB CT SCAN (04/17): NO EVIDENCE OF ACUTE APPENDICITIS OR ANY ACUTE INTRA-ABDOMINAL PROCESS. REPEAT TROP I (04/16): 0.89.

COURSE IN THE WARD:
ON THE DAY OF ADMISSION (04/15): ADMITTED UNDER THE SERVICE OF INTERNAL MEDICINE. PATIENT TEMPORARILY PLACED ON HEPLOCK AND LSLF DIET. HOOKED TO O2 SUPPORT 2LPM VIA NASAL CANNULA. APPROPRIATE DIAGNOSTICS DONE. FOR WAB CT SCAN WITH IV AND RECTAL CONTRAST. STARTED ON ASPIRIN 80MG/TAB OD, CLOPIDOGREL 75MG/TAB OD, ENALAPRIL 5MG/TAB OD, CARVEDILOL 6.25MG/TAB 1/2 TAB BID, ISMN 30MG/TAB OD, ISDN 5MG/TAB SL PRN FOR CHEST PAIN, OMEPRAZOLE 40MG/TAB OD, LACTULOSE 30ML HS, ATORVASTATIN 80MG/TAB OD HS, ENOXAPARIN 0.6ML SC Q12.
ON THE 1ST HOSPITAL DAY (04/16): KEPT ON HEPLOCK. STILL FOR WAB CT SCAN. STARTED ON HYDROCORTISONE 20MG IV 1 HR PRIOR TO CT SCAN AND DIPHENHYDRAMINE 50MG IV 1 HR PRIOR TO CT SCAN. CONTINUED PRESENT MANAGEMENT.
ON THE 2ND HOSPITAL DAY (04/17): CT SCAN DONE. CONTINUED PRESENT MANAGEMENT AND MEDICATIONS.
ON THE 3RD TO 7TH HOSPITAL DAY (04/18-04/22): CONTINUED PRESENT MANAGEMENT. SERIAL ABDOMINAL EXAMINATION DONE. APPENDECTOMY DEFERRED AS PAIN RESOLVED AND CT SCAN NEGATIVE.
ON THE 8TH HOSPITAL DAY (04/23): PATIENT DEEMED FIT AND CLEARED FOR DISCHARGE.

HOME MEDICATIONS:
1. ASA 80MG/TAB ONCE A DAY AFTER LUNCH
2. CLOPIDOGREL 75MG/TAB ONCE A DAY AFTER LUNCH
3. ENALAPRIL 5MG/TAB ONCE A DAY
4. CARVEDILOL 6.25MG/TAB 1/2 TAB TWICE A DAY
5. ISMN 30MG/TAB ONCE A DAY
6. ISDN 5MG/TAB SUBLINGUAL PRN FOR CHEST PAIN
7. ATORVASTATIN 80MG/TAB ONCE A DAY BEFORE BED TIME

INSTRUCTIONS:
- MAINTAIN DIET LOW SALT LOW FAT
- STRICT MEDICINE COMPLIANCE

FOLLOW-UP:
- FOLLOW UP AT QMMC IM-TELEOPD AFTER 1 WEEK ON MAY 1, 2023
- REPEAT 2D ECHOCARDIOGRAPHY WITHIN 4 WEEKS
- REPEAT CREATININE AND ELECTROLYTES AFTER 2 WEEKS
- CARDIOLOGY CONSULT IF CHEST PAIN RECURS
"""

VISIT_2 = """QUIRINO MEMORIAL MEDICAL CENTER
DISCHARGE SUMMARY / MEDICAL ABSTRACT

NAME: GALICIA, DEOGRACIAS JR.
AGE: 53  SEX: M  STATUS: MARRIED  HOSPITAL NO: 978305
SERVICE/S: MEDICINE  ROOM/WARD: WARD 4
ATTENDING PHYSICIAN: DR. PAREJA, NOEL JOSEPH S.
DATE ADMITTED: 10/08/23  TIME ADMITTED: 08:20 AM
DATE DISCHARGED: 10/15/23
CONDITION UPON DISCHARGE: [x] IMPROVED

ADMITTING DIAGNOSIS: ACUTE CORONARY SYNDROME NON ST ELEVATION MYOCARDIAL INFARCTION INFERIOR WALL TIMI 3 KILIP 2 GRACE SCORE 112; CONGESTIVE HEART FAILURE WITH REDUCED EJECTION FRACTION (LVEF 40%); HYPERTENSIVE HEART DISEASE; CEREBROVASCULAR DISEASE BLEED MRS 3, S/P DECOMPRESSIVE HEMICRANIECTOMY LEFT (2015, QMMC)

FINAL DIAGNOSIS: ACUTE CORONARY SYNDROME NON ST ELEVATION MYOCARDIAL INFARCTION INFERIOR WALL TIMI 3 KILIP 2 GRACE SCORE 98; CONGESTIVE HEART FAILURE WITH REDUCED EJECTION FRACTION (LVEF 40%); HYPERTENSIVE HEART DISEASE; CEREBROVASCULAR DISEASE BLEED MRS 3, S/P DECOMPRESSIVE HEMICRANIECTOMY LEFT (2015, QMMC)

CHIEF COMPLAINT: CHEST PAIN WITH SHORTNESS OF BREATH

HISTORY OF PRESENT ILLNESS: 2 DAYS PTA, PATIENT NOTED RECURRENCE OF CHEST PAIN, DESCRIBED AS PRESSURE-LIKE, RADIATING TO LEFT ARM, ASSOCIATED WITH SHORTNESS OF BREATH ON EXERTION. ALSO NOTED BILATERAL ANKLE EDEMA FOR 1 WEEK PRIOR TO ADMISSION. TOOK ISDN 5MG SL WITH PARTIAL RELIEF. PERSISTENCE OF SYMPTOMS PROMPTED CONSULT.

PAST MEDICAL HISTORY: HYPERTENSION (2015), NSTEMI SEPTAL WALL (APRIL 2023) - DISCHARGED ON ASA 80MG, CLOPIDOGREL 75MG, ENALAPRIL 5MG, CARVEDILOL 6.25MG, ISMN 30MG, ATORVASTATIN 80MG; CHRONIC CVD INFARCT (2015) - S/P DECOMPRESSIVE HEMICRANIECTOMY (2015, QMMC)

PHYSICAL EXAMINATION: BP 160/100, HR 96, RR 22, TEMP 36.8, SpO2 94% ON ROOM AIR. AWAKE, COHERENT, IN MILD RESPIRATORY DISTRESS. ANICTERIC SCLERAE, PALE PALPEBRAL CONJUNCTIVAE. SYMMETRIC CHEST EXPANSION, BILATERAL CRACKLES AT LUNG BASES. ADYNAMIC PRECORDIUM, SOFT S3 GALLOP, NO MURMURS. ABDOMEN SOFT. BILATERAL PIT EDEMA (+2), LOWER EXTREMITIES.

LABORATORY DATA:
CBC (10/08): WBC 11.2, HGB 118, HCT 0.36, PLT 198. TROP I (10/08): 2.34 (H). CKMB (10/08): 31 (H). CREATININE (10/08): 1.4 MG/DL. POTASSIUM (10/08): 3.1 MEQ/L (L). SODIUM (10/08): 135 MEQ/L. BNP (10/08): 890 PG/ML (H). ECG (10/08): NSR WITH ST DEPRESSION LEADS II III AVF, T WAVE INVERSION V4-V6. 2D ECHO (10/10): LVEF 40%, CONCENTRIC LVH, GRADE II DIASTOLIC DYSFUNCTION. CHEST X-RAY (10/08): CARDIOMEGALY, BILATERAL PLEURAL EFFUSION, MILD PULMONARY EDEMA.

COURSE IN THE WARD:
ON THE DAY OF ADMISSION (10/08): ADMITTED UNDER THE SERVICE OF INTERNAL MEDICINE. PLACED ON LSLF DIET AND FLUID RESTRICTION 1.5L/DAY. STARTED ON O2 SUPPORT 3LPM VIA NASAL CANNULA. CONTINUED ASA 80MG OD, CLOPIDOGREL 75MG OD, ENALAPRIL 5MG OD, CARVEDILOL 6.25MG BID, ISMN 30MG OD, ATORVASTATIN 80MG OD. ADDED FUROSEMIDE 40MG IV OD FOR DIURESIS AND SPIRONOLACTONE 25MG TAB OD. ENOXAPARIN 0.6ML SC Q12 STARTED. POTASSIUM SUPPLEMENTATION STARTED (KCL 600MG TID).
ON THE 1ST TO 3RD HOSPITAL DAY (10/09-10/11): GRADUAL IMPROVEMENT IN RESPIRATORY STATUS. EDEMA RESOLVING. REPEAT TROP I (10/09): 1.87 (H), DOWNTRENDING. POTASSIUM CORRECTED TO 3.8 MEQ/L. O2 SUPPORT WEANED. FUROSEMIDE SHIFTED TO ORAL 40MG OD UPON CLINICAL IMPROVEMENT.
ON THE 4TH TO 6TH HOSPITAL DAY (10/12-10/14): CONTINUED PRESENT MANAGEMENT. PATIENT AMBULATING. HEMODYNAMICALLY STABLE. BILATERAL CRACKLES RESOLVED. EDEMA MINIMAL.
ON THE 7TH HOSPITAL DAY (10/15): PATIENT DEEMED FIT AND CLEARED FOR DISCHARGE.

HOME MEDICATIONS:
1. ASA 80MG/TAB ONCE A DAY AFTER LUNCH
2. CLOPIDOGREL 75MG/TAB ONCE A DAY AFTER LUNCH
3. ENALAPRIL 5MG/TAB ONCE A DAY
4. CARVEDILOL 6.25MG/TAB 1/2 TAB TWICE A DAY
5. ISMN 30MG/TAB ONCE A DAY
6. ISDN 5MG/TAB SUBLINGUAL PRN FOR CHEST PAIN
7. ATORVASTATIN 80MG/TAB ONCE A DAY BEFORE BED TIME
8. FUROSEMIDE 40MG/TAB ONCE A DAY
9. SPIRONOLACTONE 25MG/TAB ONCE A DAY

INSTRUCTIONS:
- DAILY WEIGHT MONITORING, CONSULT IF WEIGHT GAIN MORE THAN 2KG IN 2 DAYS
- STRICT FLUID RESTRICTION 1.5L PER DAY
- LOW SALT LOW FAT DIET
- STRICT MEDICINE COMPLIANCE

FOLLOW-UP:
- FOLLOW UP AT QMMC CARDIOLOGY OPD AFTER 1 WEEK ON OCTOBER 22, 2023
- REPEAT 2D ECHOCARDIOGRAPHY AFTER 3 MONTHS
- REPEAT BNP AND CREATININE AFTER 2 WEEKS
- REPEAT POTASSIUM AFTER 1 WEEK
"""

VISIT_3 = """QUIRINO MEMORIAL MEDICAL CENTER
DISCHARGE SUMMARY / MEDICAL ABSTRACT

NAME: GALICIA, DEOGRACIAS JR.
AGE: 54  SEX: M  STATUS: MARRIED  HOSPITAL NO: 978305
SERVICE/S: MEDICINE - CARDIOLOGY  ROOM/WARD: WARD 4
ATTENDING PHYSICIAN: DR. PAREJA, NOEL JOSEPH S.
DATE ADMITTED: 03/05/24  TIME ADMITTED: 02:30 PM
DATE DISCHARGED: 03/14/24
CONDITION UPON DISCHARGE: [x] IMPROVED

ADMITTING DIAGNOSIS: ACUTE DECOMPENSATED HEART FAILURE WITH REDUCED EJECTION FRACTION (LVEF 35%); HYPERTENSIVE URGENCY; CHRONIC KIDNEY DISEASE STAGE 2; CEREBROVASCULAR DISEASE BLEED MRS 3, S/P DECOMPRESSIVE HEMICRANIECTOMY LEFT (2015, QMMC); POST NSTEMI (APRIL 2023, OCTOBER 2023)

FINAL DIAGNOSIS: ACUTE DECOMPENSATED HEART FAILURE WITH REDUCED EJECTION FRACTION (LVEF 35%); HYPERTENSIVE URGENCY, CONTROLLED; CHRONIC KIDNEY DISEASE STAGE 2; CEREBROVASCULAR DISEASE BLEED MRS 3, S/P DECOMPRESSIVE HEMICRANIECTOMY LEFT (2015, QMMC); POST NSTEMI

CHIEF COMPLAINT: SEVERE SHORTNESS OF BREATH AND LEG SWELLING

HISTORY OF PRESENT ILLNESS: 5 DAYS PTA, PATIENT NOTED PROGRESSIVE WORSENING OF DYSPNEA NOW OCCURRING AT REST, ORTHOPNEA 3-PILLOW, PAROXYSMAL NOCTURNAL DYSPNEA, AND MARKED INCREASE IN BILATERAL LEG EDEMA. ADMITTED WEIGHT GAIN OF 5KG OVER 2 WEEKS. ALSO NOTED DECREASED URINE OUTPUT. COMPLIANCE TO FUROSEMIDE QUESTIONED - PATIENT ADMITTED MISSING DOSES DUE TO COST. CONSULT SOUGHT DUE TO INABILITY TO LIE FLAT.

PAST MEDICAL HISTORY: HYPERTENSION (2015), NSTEMI SEPTAL WALL (APRIL 2023), NSTEMI INFERIOR WALL WITH CHFrEF LVEF 40% (OCTOBER 2023) - DISCHARGED ON ASA 80MG, CLOPIDOGREL 75MG, ENALAPRIL 5MG, CARVEDILOL 6.25MG, ISMN 30MG, ATORVASTATIN 80MG, FUROSEMIDE 40MG, SPIRONOLACTONE 25MG; CHRONIC CVD INFARCT (2015) - S/P DECOMPRESSIVE HEMICRANIECTOMY (2015, QMMC)

PHYSICAL EXAMINATION: BP 175/105, HR 108, RR 26, TEMP 36.5, SpO2 90% ON ROOM AIR. AWAKE, COHERENT, IN MODERATE RESPIRATORY DISTRESS. ANICTERIC SCLERAE, PALE PALPEBRAL CONJUNCTIVAE. DISTENDED NECK VEINS AT 45 DEGREES. BILATERAL CRACKLES UP TO MIDDLE LUNG FIELDS. ADYNAMIC PRECORDIUM, S3 GALLOP PRESENT, DISPLACED PMI 6TH ICS MCL. ABDOMEN SOFT, HEPATOMEGALY. BILATERAL PIT EDEMA (+3), UPPER THIGH LEVEL.

LABORATORY DATA:
CBC (03/05): WBC 8.9, HGB 107, HCT 0.32, PLT 210. CREATININE (03/05): 1.8 MG/DL (H). POTASSIUM (03/05): 3.5 MEQ/L. SODIUM (03/05): 132 MEQ/L (L). BNP (03/05): 2240 PG/ML (H). URIC ACID (03/05): 8.2 MG/DL (H). ECG (03/05): SINUS TACHYCARDIA, LBBB PATTERN, LVH BY VOLTAGE CRITERIA. 2D ECHO (03/07): LVEF 35% (REDUCED FROM 40%), SEVERE CONCENTRIC LVH, GRADE III DIASTOLIC DYSFUNCTION, MILD MITRAL REGURGITATION. CHEST X-RAY (03/05): MARKED CARDIOMEGALY, BILATERAL PLEURAL EFFUSION MODERATE, PULMONARY EDEMA. CREATININE (03/12): 1.6 MG/DL, IMPROVING.

COURSE IN THE WARD:
ON THE DAY OF ADMISSION (03/05): ADMITTED UNDER MEDICINE-CARDIOLOGY. PLACED ON STRICT FLUID RESTRICTION 1L/DAY, LSLF DIET. O2 SUPPORT STARTED AT 5LPM VIA FACE MASK. IV FUROSEMIDE 80MG BID STARTED FOR AGGRESSIVE DIURESIS. HELD ENALAPRIL DUE TO ELEVATED CREATININE AND HYPOTENSION RISK. CARVEDILOL DOSE REDUCED TO 3.125MG BID DUE TO TACHYCARDIA AND HEMODYNAMIC INSTABILITY. CONTINUED ASA 80MG OD, ATORVASTATIN 80MG OD, SPIRONOLACTONE 25MG OD. CLOPIDOGREL DISCONTINUED DUE TO BLEEDING RISK REASSESSMENT AT 1 YEAR POST NSTEMI. DIGOXIN 0.125MG OD ADDED FOR RATE CONTROL AND INOTROPIC SUPPORT.
ON THE 1ST TO 3RD HOSPITAL DAY (03/06-03/08): URINE OUTPUT IMPROVING WITH IV DIURETICS. WEIGHT DECREASING 1-1.5KG/DAY. SpO2 IMPROVING TO 95-96%. BILATERAL CRACKLES DECREASING. BP CONTROLLED 130-140/80-90. ENALAPRIL RE-INTRODUCED AT 2.5MG OD AS CREATININE STABILIZING.
ON THE 4TH TO 7TH HOSPITAL DAY (03/09-03/12): SHIFTED TO ORAL FUROSEMIDE 80MG BID. O2 WEANED. PATIENT AMBULATING. REPEAT BNP (03/10): 980 PG/ML, SIGNIFICANT IMPROVEMENT. REPEAT CREATININE (03/12): 1.6, IMPROVING. SODIUM CORRECTED TO 136 MEQ/L. CARVEDILOL UPTITRATED BACK TO 6.25MG BID.
ON THE 8TH TO 9TH HOSPITAL DAY (03/13-03/14): CONTINUED PRESENT MANAGEMENT. WEIGHT STABLE. EDEMA RESOLVED. PATIENT DEEMED FIT FOR DISCHARGE.

HOME MEDICATIONS:
1. ASA 80MG/TAB ONCE A DAY AFTER LUNCH
2. ENALAPRIL 2.5MG/TAB ONCE A DAY (DOSE REDUCED FROM 5MG - MONITOR CREATININE)
3. CARVEDILOL 6.25MG/TAB 1/2 TAB TWICE A DAY
4. ATORVASTATIN 80MG/TAB ONCE A DAY BEFORE BED TIME
5. FUROSEMIDE 80MG/TAB TWICE A DAY (DOSE INCREASED FROM 40MG OD)
6. SPIRONOLACTONE 25MG/TAB ONCE A DAY
7. DIGOXIN 0.125MG/TAB ONCE A DAY
8. ISDN 5MG/TAB SUBLINGUAL PRN FOR CHEST PAIN

NOTE: CLOPIDOGREL DISCONTINUED. ISMN DISCONTINUED (REPLACED BY DIGOXIN FOR RATE CONTROL).

INSTRUCTIONS:
- DAILY WEIGHT MONITORING - CONSULT IMMEDIATELY IF WEIGHT GAIN MORE THAN 1KG IN 1 DAY
- STRICT FLUID RESTRICTION 1L PER DAY
- LOW SALT LOW FAT DIET NO ADDED SALT
- STRICT MEDICINE COMPLIANCE - EMPHASIZE IMPORTANCE OF FUROSEMIDE
- MONITOR FOR DIGOXIN TOXICITY: NAUSEA, VOMITING, VISUAL CHANGES, IRREGULAR HEARTBEAT

FOLLOW-UP:
- FOLLOW UP AT QMMC CARDIOLOGY OPD AFTER 1 WEEK ON MARCH 21, 2024
- REPEAT 2D ECHOCARDIOGRAPHY AFTER 3 MONTHS (JUNE 2024)
- REPEAT CREATININE, ELECTROLYTES, AND DIGOXIN LEVEL AFTER 1 WEEK
- REPEAT BNP AFTER 1 MONTH
- NEPHROLOGY REFERRAL FOR CKD STAGE 2 MONITORING
"""

VISITS = [
    ("discharge_2023_04_visit1.pdf", "VISIT 1 — Apr 2023", VISIT_1),
    ("discharge_2023_10_visit2.pdf", "VISIT 2 — Oct 2023", VISIT_2),
    ("discharge_2024_03_visit3.pdf", "VISIT 3 — Mar 2024", VISIT_3),
]


def build_pdf(filepath: str, title: str, content: str) -> None:
    doc = SimpleDocTemplate(
        filepath,
        pagesize=LETTER,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    body_style = ParagraphStyle(
        "body",
        parent=styles["Normal"],
        fontSize=9,
        leading=13,
        fontName="Courier",
        spaceAfter=4,
    )
    header_style = ParagraphStyle(
        "header",
        parent=styles["Normal"],
        fontSize=11,
        leading=14,
        fontName="Courier-Bold",
        alignment=TA_CENTER,
        spaceAfter=8,
    )

    story = []
    story.append(Paragraph(title, header_style))
    story.append(Spacer(1, 0.1 * inch))

    for line in content.strip().split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.06 * inch))
        else:
            story.append(Paragraph(line, body_style))

    doc.build(story)
    print(f"  Created: {filepath}")


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"Output folder: {OUT_DIR}\n")

    for filename, title, content in VISITS:
        filepath = os.path.join(OUT_DIR, filename)
        build_pdf(filepath, title, content)

    print(f"\nDone — {len(VISITS)} discharge PDFs generated.")
    print(f"Patient folder: {OUT_DIR}")
    print("\nIn CLARA, select patient 'GALICIA_DEOGRACIAS_JR' to test EncountersPanel.")


if __name__ == "__main__":
    main()
